require "mrcharlss.options"
require "mrcharlss.plugins"
require "mrcharlss.colorscheme"
require "mrcharlss.cmp"
require "mrcharlss.autopairs"
require "mrcharlss.treesitter"
require "mrcharlss.gitsigns"
require "mrcharlss.impatient"
require "mrcharlss.autocommands"
require "mrcharlss.telescope"
require "mrcharlss.comment"
require "mrcharlss.lsp"
require "mrcharlss.keymaps"
require "mrcharlss.bufferline"
require "mrcharlss.dap"


